# Generated by Django 3.2.14 on 2022-09-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cumpleanios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='articulos')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Cumpleaños',
                'verbose_name_plural': 'Cumpleaños',
            },
        ),
        migrations.CreateModel(
            name='Decoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='articulos')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Decoracion',
                'verbose_name_plural': 'Decoracion',
            },
        ),
        migrations.CreateModel(
            name='Descartables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='articulos')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Descartables',
                'verbose_name_plural': 'Descartables',
            },
        ),
        migrations.CreateModel(
            name='DisfracesYaccesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='articulos')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Disfraces Y Accesorios',
                'verbose_name_plural': 'Disfraces Y Accesorios',
            },
        ),
        migrations.CreateModel(
            name='Reposteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='articulos')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Reposteria',
                'verbose_name_plural': 'Reposteria',
            },
        ),
    ]
