# Generated by Django 3.2.14 on 2022-09-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.DeleteModel(
            name='Cumpleanios',
        ),
        migrations.DeleteModel(
            name='Decoracion',
        ),
        migrations.DeleteModel(
            name='Descartables',
        ),
        migrations.DeleteModel(
            name='DisfracesYaccesorios',
        ),
        migrations.DeleteModel(
            name='Reposteria',
        ),
        migrations.AddField(
            model_name='articulos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categorias'),
        ),
    ]
