# Generated by Django 3.2.14 on 2022-12-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20221203_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='articulo_id',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
    ]
