# Generated by Django 3.2.14 on 2022-07-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roque_vago_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
    ]
