# Generated by Django 3.2.14 on 2022-08-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roque_vago_app', '0002_alter_articulo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
