# Generated by Django 3.2.14 on 2022-09-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roque_vago_app', '0005_auto_20220805_1956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cumpleanios',
        ),
        migrations.DeleteModel(
            name='Decoracion',
        ),
        migrations.DeleteModel(
            name='Descartables',
        ),
        migrations.DeleteModel(
            name='DisfracesYaccesorios',
        ),
        migrations.DeleteModel(
            name='Reposteria',
        ),
    ]
